package ir.infosphere.sport.enm;

public enum PermissionEnum {
	
	USER_Package(2),
	USER_List(16),
	USER_New(12),
	USER_Edit(13),
	USER_Delete(19),
	USER_Activation(18),
	USER_Approve(17),
	USER_NewPass(240),
	USER_EditAdmin(241),
	USER_AddGroup(20),
	USER_Group_Package(21),
	USER_Group_List(76),
	USER_Group_New(77),
	USER_Group_Permission(78),
	USER_Group_Activation(79),
	USER_Group_Edit(80),
	USER_Group_Delete(81),
	USER_DarkhasteKartGorohi(261),
	USER_DarkhasteKartGorohiRaygan(300),
	USER_PardakhtHagheOzviatGorohi(294),
	
	USER_Portal_Access(216),
	USER_Ostan_Access(217),
	USER_Madrese_Access(302),
	
	MADRESE_Package(137),
	MADRESE_List(195),
	MADRESE_New(139),
	MADRESE_Edit(140),
	MADRESE_Delete(141),
	MADRESE_Activation(142),
	MADRESE_Ozv(143),
	MADRESE_Ozv_New(144),
	MADRESE_Ozv_Show_Sabeghe(145),
	MADRESE_Ozv_Edit(146),
	MADRESE_Ozv_Delete(147),
	MADRESE_Ozv_Exit(148),
	MADRESE_FormeArzeshyabi(149),
	MADRESE_FormeArzeshyabi_New(150),
	MADRESE_FormeArzeshyabi_Delete(152),
	MADRESE_KoleKeshvar(193),
	MADRESE_KoleOstan(194),
	
	TIM_Package(5),
	TIM_List(42),
	TIM_New(43),
	TIM_Edit(45),
	TIM_Activation(46),
	TIM_Delete(47),
	TIM_Ozv(48),
	TIM_Ozv_List(109),
	TIM_Ozv_New(110),
	TIM_Ozv_Edit(111),
	TIM_Ozv_Activation(112),
	TIM_Ozv_Delete(113),
	TIM_Ozv_Exit(44),
	TIM_Ozv_Sabeghe(229),
	TIM_KoleKeshvar(234),
	TIM_KoleOstan(235),
	
	SIASAT_Package(153),
	SIASAT_List(196),
	SIASAT_New(154),
	SIASAT_Edit(155),
	SIASAT_Delete(156),
	SIASAT_Activation(157),
	
	GOZARESHAT_Madrese_package(206),
	GOZARESHAT_Madrese_FormeArzeshyabiBeTafkikeSal(207),
	GOZARESHAT_Madrese_FormeArzeshyabiBeTafkikeOstan(208),
	GOZARESHAT_Madrese_FormeArzeshyabiList(209),
	GOZARESHAT_Madrese_ListeMadaresSabtShodeVaTedadAza(242),
	GOZARESHAT_Madrese_SavabeghAzayeMadrese(243),
	GOZARESHAT_Madrese_Pardakht_Karbaran(244),
	GOZARESHAT_Madrese_VaziatePardakhtHagheOzviat(245),
	GOZARESHAT_Madrese_Tajmiee(262),
	
	GOZARESHAT_TIM_package(220),
	GOZARESHAT_TIM_listTIM(221),
	GOZARESHAT_TIM_listOzv(222),
	GOZARESHAT_TIM_Pardakht(223),
	GOZARESHAT_PARDAKHT_KARBARAN_TIM(230),
	GOZARESHAT_TIM_Tajmiee(309),
	
	AKHBAR_Ostani(211),
	GALLERY_Ostani(212),
	AKHBAR_PORTAL(214),
	GALLERY_PORTAL(213),
	AKHBAR_MADRESE(218),
	GALLERY_MADRESE(219),
	
	MATLAB_Package(158),
	MATLAB_DarbareMa(159),
	MATLAB_TamasBaMa(160),
	MATLAB_PorseshHayeMotedavel(231),
	MATLAB_RahnamayeSite(232),
	MATLAB_News_Package(161),
	MATLAB_News_List(198),
	MATLAB_News_Category_New(162),
	MATLAB_News_Category_Edit(163),
	MATLAB_News_Category_Delete(164),
	MATLAB_News_New(165),
	MATLAB_News_Edit(166),
	MATLAB_News_Delete(167),
	MATLAB_News_Activation(236),
	MATLAB_Hamayesh_Package(168),
	MATLAB_Hamayesh_List(199),
	MATLAB_Hamayesh_Category_New(169),
	MATLAB_Hamayesh_Category_Edit(170),
	MATLAB_Hamayesh_Category_Delete(171),
	MATLAB_Hamayesh_New(172),
	MATLAB_Hamayesh_Edit(173),
	MATLAB_Hamayesh_Delete(174),
	MATLAB_Gallery_Package(175),
	MATLAB_Gallery_List(197),
	MATLAB_Gallery_New(176),
	MATLAB_Gallery_Edit(177),
	MATLAB_Gallery_Delete(178),
	MATLAB_Gallery_ImageNew(179),
	MATLAB_Gallery_ImageDelete(180),
	MATLAB_AeenName_Package(181),
	MATLAB_AeenName_List(202),
	MATLAB_AeenName_New(182),
	MATLAB_AeenName_Edit(183),
	MATLAB_AeenName_Delete(184),
	MATLAB_Maghale_Package(185),
	MATLAB_Maghale_List(200),
	MATLAB_Maghale_New(186),
	MATLAB_Maghale_Edit(187),
	MATLAB_Maghale_Delete(188),
	MATLAB_Link_Package(189),
	MATLAB_Link_List(201),
	MATLAB_Link_New(190),
	MATLAB_Link_Edit(191),
	MATLAB_Link_Delete(192),
	
	MATLAB_Slid_Package(274),
	MATLAB_Slid_List(275),
	MATLAB_Slid_New(276),
	MATLAB_Slid_Edit(277),
	MATLAB_Slid_Delete(278),
	
	VARZESHGAH_Package(3),
	VARZESHGAH_View(22),
	VARZESHGAH_New(23),
	VARZESHGAH_Edit(24),
	VARZESHGAH_Activation(25),
	VARZESHGAH_Delete(26),
	
	VARZESHGAH_Bakhsh_Package(28),
	VARZESHGAH_Bakhsh_List(82),
	VARZESHGAH_Bakhsh_New(83),
	VARZESHGAH_Bakhsh_Edit(84),
	VARZESHGAH_Bakhsh_Delete(85),
	VARZESHGAH_Bakhsh_Activation(86),

	VARZESHGAH_Bakhsh_TarifTaghvim(95),
	VARZESHGAH_Bakhsh_TarifSansRoyeTaghvim(96),
	
	VARZESHGAH_Service_Package(29),
	VARZESHGAH_Service_List(87),
	VARZESHGAH_Service_New(89),
	VARZESHGAH_Service_Edit(90),
	VARZESHGAH_Service_Delete(91),
	VARZESHGAH_Service_Activation(92),
	VARZESHGAH_Service_Sans(88),
	VARZESHGAH_Service_ViewTozihat(93),
	VARZESHGAH_Service_EditOzviat(94),
	
	VARZESHGAH_Sans_Package(108),
	VARZESHGAH_Sans_List(263),
	VARZESHGAH_Sans_New(264),
	VARZESHGAH_Sans_Edit(265),
	VARZESHGAH_Sans_Delete(266),
	VARZESHGAH_Sans_Activation(267),
	
	VARZESHGAH_Taghvim_New(95),
	VARZESHGAH_Taghvim_SansNew(96),
	
	VARZESHGAH_Mogheiat_Package(31),
	VARZESHGAH_Mogheiat_List(97),
	VARZESHGAH_Mogheiat_New(98),
	VARZESHGAH_Mogheiat_Edit(99),
	VARZESHGAH_Mogheiat_Activation(100),
	VARZESHGAH_Mogheiat_Delete(101),
	
	VARZESHGAH_Bolook_Package(32),
	VARZESHGAH_Bolook_List(102),
	VARZESHGAH_Bolook_New(103),
	VARZESHGAH_Bolook_Edit(104),
	VARZESHGAH_Bolook_Delete(105),
	VARZESHGAH_Bolook_Activation(106),
	
	VARZESHGAH_Bolook_Radif_Package(107),
	VARZESHGAH_Bolook_Radif_New(224),
	VARZESHGAH_Bolook_Radif_Edit(225),
	VARZESHGAH_Bolook_Radif_Delete(226),
	VARZESHGAH_Bolook_Radif_Activation(227),
	
	BAZI_Package(4),
	BAZI_List(33),
	BAZI_New(34),
	BAZI_Edit(35),
	BAZI_CopySetting(308),
	BAZI_Delete(36),
	BAZI_VaziateMogheiat(37),
	BAZI_VaziateBolook(38),
	BAZI_IjadeBelit(39),
	BAZI_TakhsiseSandali(40),
	BAZI_BelitActivation(41),
	BAZI_Laghv(228),
	BAZI_GozaresheMali(238),
	BAZI_GozaresheTedadi(312),

	GOZARESHAT_MALI_Package(11),
	GOZARESHAT_MALI_GozaresheTarakonesheMalieTarafeGharardad(71),
	GOZARESHAT_MALI_GozaresheSavabegheTarakoneshhayeKart(72),
	GOZARESHAT_MALI_GozaresheVaziateKart(73),
	GOZARESHAT_MALI_GozaresheSavabegheTarakoneshhayeKarbar(74),
	GOZARESHAT_MALI_GozaresheSavabegheTarakoneshhayeMalieHesab(75),
	GOZARESHAT_MALI_GozaresheForoosheKart(239),
	GOZARESHAT_MALI_GozaresheForoosheBelit(313),
	
	TARAFEGHARARDAD_Package(6),
	TARAFEGHARARDAD_List(49),
	TARAFEGHARARDAD_New(50),
	TARAFEGHARARDAD_Edit(51),
	TARAFEGHARARDAD_Activation(52),
	TARAFEGHARARDAD_Delete(53),
	
	TARAFEGHARARDAD_Hesab_Package(54),
	TARAFEGHARARDAD_Hesab_Tasviye(115),
	TARAFEGHARARDAD_Hesab_New(116),
	TARAFEGHARARDAD_Hesab_Edit(117),
	TARAFEGHARARDAD_Hesab_Activation(118),
	TARAFEGHARARDAD_Hesab_Delete(119),
	TARAFEGHARARDAD_Hesab_Factor_Package(120),
	TARAFEGHARARDAD_Hesab_Factor_New(268),
	TARAFEGHARARDAD_Hesab_Poz_Package(121),
	TARAFEGHARARDAD_Hesab_Poz_Delete(269),
	TARAFEGHARARDAD_Hesab_Poz_Edit(270),
	TARAFEGHARARDAD_Hesab_Poz_Esghat(273),
	TARAFEGHARARDAD_Hesab_Poz_Odat(272),
	TARAFEGHARARDAD_Hesab_Poz_Takhsis(271),
	
	GOZARESHATEBAZIVAOZVIYYAT_Package(7),
	GOZARESHATEBAZIVAOZVIYYAT_GozaresheBaziha(55),
	GOZARESHATEBAZIVAOZVIYYAT_GozaresheVaziateBelit(56),
	GOZARESHATEBAZIVAOZVIYYAT_GozaresheVaziateTamashagaran(57),
	GOZARESHATEBAZIVAOZVIYYAT_GozaresheRahgirieTamashagareKhas(58),
	GOZARESHATEBAZIVAOZVIYYAT_GozaresheOzvaiyatDarServicehayeBakhsh(59),
	GOZARESHATEBAZIVAOZVIYYAT_Rahgiri(60),
	
	POZ_Package(8),
	POZ_List(61),
	POZ_New(62),
	POZ_Edit(63),
	POZ_Esghat(64),
	POZ_Delete(65),
	
	KODING_Package(9),
	
	KODING_Navahi_Package(66),
	KODING_Navahi_List(307),
	KODING_Navahi_New(303),
	KODING_Navahi_Edit(304),
	KODING_Navahi_Delete(305),
	KODING_Navahi_Faal(306),
	
	KODING_KodingeOmoomi_Package(67),
	KODING_KodingeOmoomi_List(295),
	KODING_KodingeOmoomi_New(296),
	KODING_KodingeOmoomi_Edit(297),
	KODING_KodingeOmoomi_Delete(298),
	KODING_KodingeOmoomi_Faal(299),
	
	KODING_ReshtehayeVarzeshi_Package(68),
	KODING_ReshtehayeVarzeshi_List(284),
	KODING_ReshtehayeVarzeshi_New(285),
	KODING_ReshtehayeVarzeshi_Edit(286),
	KODING_ReshtehayeVarzeshi_Delete(287),
	KODING_ReshtehayeVarzeshi_Faal(288),
	KODING_ReshtehayeVarzeshi_Group_Package(289),
	KODING_ReshtehayeVarzeshi_Group_New(290),
	KODING_ReshtehayeVarzeshi_Group_Edit(291),
	KODING_ReshtehayeVarzeshi_Group_Delete(292),
	KODING_ReshtehayeVarzeshi_Group_Faal(293),
	
	PEYKAREBANDI_Package(10),
	PEYKAREBANDI_Tanzimat(69),
	PEYKAREBANDI_SiasathayeTakhfif(70),
	
	BASTEFOROSH_Package(246),
	BASTEFOROSH_List(247),
	BASTEFOROSH_New(248),
	BASTEFOROSH_Edit(249),
	BASTEFOROSH_Delete(250),
	BASTEFOROSH_Activation(251),
	BASTEFOROSH_NamayeshAza(252),
	
	BASTETAKHFIF_Package(253),
	BASTETAKHFIF_List(254),
	BASTETAKHFIF_New(255),
	BASTETAKHFIF_Delete(257),
	BASTETAKHFIF_Belit_Package(258),
	BASTETAKHFIF_Kart_Package(259),
	BASTETAKHFIF_Service_Package(260),
	BASTETAKHFIF_Activation(301),
	
	BASTEBELITESAZMANI_Package(279),
	BASTEBELITESAZMANI_TaeedeDarkhast(280),
	BASTEBELITESAZMANI_RadeDarkhast(281),
	BASTEBELITESAZMANI_KharideDarkhast(282),
	BASTEBELITESAZMANI_ViewDarkhast(283);
	
	
	private Integer permissionCode;
 
	private PermissionEnum(Integer s) {
		permissionCode = s;
	}
 
	public Integer getPermissionCode() {
		return permissionCode;
	}
}